# Generated by Django 5.0.1 on 2024-02-11 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=221)),
                ('email', models.EmailField(blank=True, max_length=221, null=True)),
                ('subject', models.CharField(max_length=221)),
                ('message', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
