# Generated by Django 5.0.1 on 2024-02-11 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comment',
            new_name='Contact',
        ),
    ]
