# Generated by Django 5.0.1 on 2024-02-17 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('episode', '0006_alter_comment_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='EpisodeFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('filter', models.CharField(max_length=221)),
                ('display', models.CharField(max_length=221)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='episode',
            name='filter',
            field=models.ManyToManyField(to='episode.episodefilter'),
        ),
    ]
